# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-


def build(bld):
    obj = bld.create_ns3_program(
        'composite-energy-model-example',
        ['core', 'network', 'energy', 'mobility', 'wifi', 'composite-energy'])
    obj.source = 'composite-energy-model-example.cc'
